### ISSUE TITLE
Design layout and template

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#11]
The current homepage design, as of ticket filing, is this:

![oversight3](https://cloud.githubusercontent.com/assets/4592/3789769/b9a41e86-1ac0-11e4-8fca-64111f5b52e0.png)

It's pretty bad. We could really use a better aesthetic and overall template for the app, that any page can fit safely and snugly into.

**Comment by heyitsolivia** [comment]
Exploring some color palette options

<img width="863" alt="screen shot 2016-01-16 at 6 21 15 pm" src="https://cloud.githubusercontent.com/assets/1198350/12375022/0f6c49fa-bc7e-11e5-9497-bfa29683d61f.png">

**Comment by konklone** [comment]
The top one looks more coherent to me, but I'm mildly concerned that it would look too much like the [US Web Design Standards](https://playbook.cio.gov/designstandards/). Let's go with the bottom one for now and iterate from there?

**Comment by heyitsolivia** [comment]
Sketches/wireframes from earlier discussions — just leaving them here as reference for now:

![img_20160116_155328](https://cloud.githubusercontent.com/assets/1198350/12375326/6aaac168-bc8b-11e5-975a-8dacb93f255c.jpg)
![homepage](https://cloud.githubusercontent.com/assets/1198350/12375327/6e3129ee-bc8b-11e5-8171-473dcd1e508f.png)
![search](https://cloud.githubusercontent.com/assets/1198350/12375328/7035ec84-bc8b-11e5-844d-81b4319de525.png)

**Comment by heyitsolivia** [comment]
**Element board**
Starting to define look and feel via an element board, where we can start to visualize UI components and their different states. This is useful for conveying how a component like navigation would adapt to varying screen sizes, and what hover or active states of nav items would look like. We can also see how typography might get applied across different components.
![oversight-elements](https://cloud.githubusercontent.com/assets/1198350/12375696/3bea368a-bc9d-11e5-8b57-8f3b925c26de.jpg)
---
**Homepage design mockup**
Piecing together some components of the element board allow us to composite a mockup of the homepage. This is a first pass at what it might look like.
![oversight-homepage](https://cloud.githubusercontent.com/assets/1198350/12375712/62dceb9c-bc9e-11e5-8482-c441e89454de.jpg)

**Comment by konklone** [comment]
@heyitsolivia This is fantastic! Thank you for making these. I'll start integrating the overall styles and colors into the layout.
