### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by seabre** [konklone/oversight.garden#124]
Navigation currently looks like [this](https://cloud.githubusercontent.com/assets/42041/15134408/e306a9e4-1639-11e6-93d1-4dbce6a733c0.png) on mobile and is really hard to use. In my case, a Galaxy S6.

You *could* just have each element of the header collapse at a certain breakpoint and that would fix it. But, there are a bunch of ways to approach this that could be better. e.g. a responsive toggle menu.

Any thoughts?

**Comment by konklone** [comment]
My thoughts are that you are exactly right, and it's really just a question of how we spend our (volunteer) resources. Anything you want to do to address this will be happily reviewed and deployed!

**Comment by seabre** [comment]
OK, cool. Just wanted to spot check opinions before I proceeded down a particular path.
