### ISSUE TITLE
Switch test suite from mocha to tape

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#133]
I'd like to migrate the test suite from mocha to tape, while it is still small. This is motivated by http://www.macwright.org/2014/03/11/tape-is-cool.html, ugly use of globals, and (IMHO) a lack of any good analogue to VCR. (Compare to https://www.npmjs.com/package/tape-nock)

Edit: also `mocha -R nyan`, what gives

**Comment by konklone** [comment]
Absolutely! I use that in SHAAAAAAAAAAAAAAA: https://github.com/konklone/shaaaaaaaaaaaaa/blob/master/test/shaaaaa.js
