### ISSUE TITLE
IG dashboard - ideas welcome

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#14]
A little grid for each IG, what they provide, and how they provide it. Field ideas:

* HTTPS support
* Report metadata provided and discoverable through an API
* How far back do reports go? (and compared to when the IG was created)
* Availability of audits
* Availability of investigations
* Availability of peer reviews
* Availability of [FISMA reports](http://arts.gov/oig/reports/fisma)
* Are reports available at all? (e.g. the intelligence community)
* FOIAed reports published proactively?
* Can categories be reliably determined?
* Unique IDs
* Specific dates consistently available for individual reports

These fall into different categories, and might need some creative design (and hard choices) to make it presentable and useful.

Separately, analyzing the *contents* of IGs may make for a separate, interesting dashboard:

* Unreleased reports
* Number of total reports
* Years available

Other ideas?

**Comment by parkr** [comment]
Seems like it'd be relatively easy. Where should this data be stored and therefore pulled from? Should it be manual, or shall the importer keep track of this and update fields as necessary?

**Comment by divergentdave** [comment]
In light of unitedstates/inspectors-general#247, it would be nice to show a histogram of the dates of reports from each inspector.

**Comment by divergentdave** [comment]
Here's a sketch of a design for the dashboard, input welcome! My focus is primarily on scraper maintenance here, so this is the sort of dashboard we'd link to from READMEs, but not the homepage.

First, on the collection side, the Python scrapers accumulate exceptions thrown, HTTP error codes, reports without dates, duplicate report IDs, `git rev-parse HEAD`, and other summary information (count of reports processed, all domains visited) from each scraper. At the end of each scraper, or at the end of all scrapers, the results are serialized into JSON and HTTP PUT to a configurable endpoint. (i.e. https://oversight.garden/dashboard/upload) This upload is authenticated by way of a shared secret in a query parameter. Both the URL of the endpoint and the shared secret are configured in `admin.yml`; if not present, then none of this is collected or submitted.

When the server receives data from the scraper at this endpoint, it first checks the shared secret. If successful, the uploaded JSON is processed (i.e. adding a timestamp, splitting into appropriate documents) and indexed into another Elasticsearch index in the same cluster, just for dashboard data. Each time a new upload of scraper data is received, it will overwrite the previous data; historical scraper errors/warnings won't be retained.

The dashboard can be viewed on the website, and the server grabs all of the latest dashboard data out of Elasticsearch to render the page. Initially, the dashboard will be a list of boxes, one per inspector/scraper, color coded and sorted based on the worst severity of any item attached to each scraper. For example, if one scraper threw an exception, it will be colored red, and grouped at the top with all other scrapers that threw exceptions last time. If a scraper only has HTTP error codes, missing dates, or duplicate report IDs, but no thrown exceptions, it will be colored yellow, and be sorted below all the red scrapers. Any scrapers without any such issues, or any inspectors without a scraper in the first place, will be colored green, and appear below the rest. These will only have more generic metadata available, such as the number of reports in the database, the number of reports seen in the last scraper run, when the last scraper run was, the duration of the last run, etc.

Each of these inspector boxes can be clicked on to expand it into a larger pane with all the above-mentioned information. In the collapsed state, each box would only show name/slug, color, and time of last scraper run. Furthermore, if a scraper has exception information, the traceback will be hidden by default in another expando pane.

If the GitHub API makes it easy, it might be nice to take the `git rev-parse HEAD` output from the scrapers and indicate whether the production working directory is up to date, or whether there are changes in `master` to the different scrapers that haven't been deployed yet.

If we collect which origins each scraper requests from, we could also cross-reference these lists with the pulse.cio.gov data set to show per-inspector information on HTTPS deployment and quality.

**Comment by konklone** [comment]
This is a fantastic place to start, and I'm all for it. For one, we need _something_. But also, scraper status is the most vital area of our operations and is a signal both to volunteer help, and to IGs to make their sites more consistent and data-driven.

Pulse won't be good enough for HTTPS support for all of the IGs, given that it doesn't yet have subdomains. But I'm happier to take this as impetus to fix that.

**Comment by divergentdave** [comment]
Things are coming along swimmingly!

![screen shot 2016-06-10 at 19 51 22](https://cloud.githubusercontent.com/assets/181772/15982074/c07cb1c4-2f44-11e6-8449-2b17fa755885.png)
