### ISSUE TITLE
ACME v2

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#194]
Let's Encrypt is rolling out ACME v2 support next year. We should upgrade when the time comes, but first we'll need a newer version of `acme-client` that supports it. Hopefully this will be as easy as bumping the gem version and changing the API endpoint we use.

https://letsencrypt.org/2017/06/14/acme-v2-api.html
http://www.rubydoc.info/gems/acme-client

**Comment by konklone** [comment]
Big :+1: from me, and sounds fun. =)

**Comment by divergentdave** [comment]
Ref: https://github.com/unixcharles/acme-client/issues/126
