### ISSUE TITLE
Per-inspector report counts are broken

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#201]
Many of the inspectors are listed as having zero reports, when that is not the case. This is affecting the inspector landing pages, because it keeps the ten latest reports from showing up on that page. This probably regressed when upgrading to ES 5.

**Comment by konklone** [comment]
Is this still the case? It's also time to upgrade to ES6.

**Comment by divergentdave** [comment]
Yes, it's still broken. I can dive back into the ES query DSL for aggregations after we upgrade, and take another look at it.
