### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#24]
There should be an option to filter searches to one agency/OIG.

**Comment by divergentdave** [comment]
Date filters would be good too

**Comment by divergentdave** [comment]
The backend for an inspector filter is done, (from #36) needs a frontend next.

**Comment by konklone** [comment]
Let's define this and consider what's worth doing.

**Comment by divergentdave** [comment]
The frontend for the inspector filter was backed out amid the redesign. Should this be re-implemented as a drop-down box again, or should we use different UI elements. (i.e. a pane of AJAX'd checkboxes?)

**Comment by konklone** [comment]
Defer to @heyitsolivia on thinking of the best way to approach filtering results by their source office.

**Comment by heyitsolivia** [comment]
@konklone @divergentdave The front end should probably reflect the most common scenario for how someone would search for reports, as well how much we want to enable/empower the user to search. I can see the former being something the default search UI we offer, while the latter could be implemented as advanced search options. (If the two end up being the same, that's also fine.)

How would someone want to search for IG reports? Some possible scenarios off the top of my head:
- I want to look for inspector reports from just one agency, matching this search term
- I want to look for inspector reports from these three specific agencies, matching this search term
- I want to look for *all* inspector reports from just one agency
- I want to look for *all* inspector reports from these three specific agencies
- I want to look for *all* inspector reports from just one agency, from the past month and a half
- I want to look for inspector reports from these three specific agencies, from a specific date range, matching this search term.

Thoughts?

**Comment by divergentdave** [comment]
> The front end should probably reflect the most common scenario for how someone would search for reports, as well how much we want to enable/empower the user to search.

Agreed. Maybe we only put the query box on the front page, and include filter controls on the search results page for refinement?

Here's my rough ranking of the scenarios. Common/likely:

- I want to look for inspector reports from just one agency, matching this search term
- I want to look for all inspector reports from just one agency

Somewhat likely:

- I want to look for inspector reports from these three specific agencies, matching this search term
- I want to look for all inspector reports from these three specific agencies
- I want to look for all inspector reports from just one agency, from the past month and a half

Unlikely:

- I want to look for inspector reports from these three specific agencies, from a specific date range, matching this search term.

**Comment by heyitsolivia** [comment]
Some mocks what search results and search filters might look like:

![oversight_search_results](https://cloud.githubusercontent.com/assets/1198350/14584669/9a93b642-041f-11e6-8f24-5a34e11c5111.jpg)

Empty states: No filters, and what "no results" might look like
![oversight_search_results_empty](https://cloud.githubusercontent.com/assets/1198350/14584670/a1bbdf08-041f-11e6-9cb4-3dd3b7007323.jpg)
