### ISSUE TITLE
Monitoring and diagnostics

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.garden#53]
Experience has shown we're in dire need of some monitoring for https://oversight.io/. We should be watching for the following things, and turning them into Slack messages, emails, or something else.
- Node process dying
- ElasticSearch process dying
- Server isn't reachable from the outside (ping, port 80, and port 443)
- 502 Gateway error and other non-OK HTTP status codes
- TLS errors from a reasonably configured client
- Errors inside Node.js from elasticsearch, express, ejs, uncaught exceptions etc. (rate limited for reporting)

While we're at it, we could also check the currently running version of Node.js against https://nodejs.org/dist/index.json from time to time, and check the current versions of npm modules against https://nodesecurity.io/.

**Comment by parkr** [comment]
Hey, Dave! I can't speak for any ideas you might have had, but at VSCO we use Datadog to monitor and alert when things look wonky. I'm not sure what the costs involved are, but simple statsd logging with alerts for errant values has worked very well for us so far. Just an idea. :-)

**Comment by divergentdave** [comment]
In the wake of [Pingdom's bad PR day](https://twitter.com/webster/status/686939721877057537), I signed up for a free StatusCake account and pointed it at the site. It should post to the Slack whenever the reports page goes down.

**Comment by divergentdave** [comment]
Almost all the problems outlined above are covered by StatusCake monitoring the /reports page, this is good enough for now.
