### ISSUE TITLE
What should the homepage have on it?

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#68]
Though I'm expecting most of our traffic to be from notifications and landing pages, the home page is still pretty important. It's just thrown together right now, and could use some clearer direction.

**Comment by heyitsolivia** [comment]
I updated the homepage search based on discussion around search filters— simple search (without advanced options) on homepage. Also updated homepage look and feel based on the search design explorations in #24 
![oversight_homepage](https://cloud.githubusercontent.com/assets/1198350/14584681/d6bf6ff8-041f-11e6-8d33-3e15b66e09a9.jpg)
