### ISSUE TITLE
Featured documents feed

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.garden#69]
When an interesting thing comes through, site owners should have an easy way to flag a particular document as Featured. We can offer that as a general filter/feed for users to look at and subscribe to.

**Comment by divergentdave** [comment]
We need to reindex back reports to get featured reports to show up on the live site. This is blocked on #101 for the moment.

**Comment by divergentdave** [comment]
Deployed! https://oversight.garden/reports/featured
